server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
spring:
  application:
    name: service-eduction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
    username: root
    password: root
  mongodb:
    uri: mongodb://name:password@//192.168.101.115:27017/test
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
    redis:
      host: localhost
      port: 6379
      jedis:
        pool:
          max-idle: 300
          max-active: 600
          max-wait: 300
mybatis:
  mapper-locations: mapper/*.xml
